name: Commit scheduler
on:
    schedule:
      - cron: '0 6 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Commit files
        run: |
          git config --local user.email "matteopietro.dazzi@gmail.com"
          git config --local user.name "iLTeoooD"
          git commit -m "Refresh of $(date +'%Y-%m-%d')" --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'