name: Build master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Dist directory
        run: mkdir img-dist
      - name: Build Alpine armhf
        env:
          ALPINE_MIRROR: http://dl-cdn.alpinelinux.org/alpine
          ARCH: armhf
        run: |
          echo "::set-env name=ARCH::armhf"
          ./docker-runner
          sudo mv dist/*img.gz img-dist
      - name: Build Alpine aarch64
        env:
          ALPINE_MIRROR: http://dl-cdn.alpinelinux.org/alpine
          ARCH: aarch64
        run: |
          echo "::set-env name=ARCH::aarch64"
          ./docker-runner
          sudo mv dist/*img.gz img-dist
      - name: Create environment variables
        run: |
          echo ::set-env name=RELEASE_TAG::"$(date +%Y_%m_%d_%H_%m)"
          echo ::set-env name=RELEASE_NAME::"$(git log --format=%B -n 1 HEAD)"
      - name: Publish release
        uses: meeDamian/github-release@1.0
        with:
          gzip: folders
          files: img-dist/
          token: ${{ secrets.GITHUB_TOKEN }}