name: Build master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build Alpine
        env:
          ALPINE_MIRROR: http://dl-cdn.alpinelinux.org/alpine
          ARCH: armhf
        run: |
          echo "::set-env name=ARCH::armhf"
          ./docker-runner
      - name: Create environment variables
        run: |
          echo ::set-env name=RELEASE_TAG::"$(date +%Y_%m_%d)_$[$(git tag | wc -l) + 1]"
          echo ::set-env name=RELEASE_NAME::"$(git log --format=%B -n 1 HEAD)"
      - name: Publish release
        uses: meeDamian/github-release@1.0
        with:
          gzip: folders
          files: dist/
          token: ${{ secrets.GITHUB_TOKEN }}